version: '3'
services:
  onboarding_project:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    container_name: onboradingProject
    restart: always
    ports:
      - "8086:80"
    volumes:
      - ../:/var/www/html
    networks:
      - pocNetwork

networks:
  pocNetwork:
    name: poc-network
    driver: bridge